name: frontend_server_common
publish_to: none
description: >-
  Frontend server integration code to use for dwds tests. Mimics flutter code.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dwds:
    path: ../dwds
  file: ^6.1.3
  logging: ^1.0.1
  meta: ^1.4.0
  mime: ^1.0.0
  shelf: ^1.1.4
  package_config: ^2.0.0
  path: ^1.8.0
  pub_semver: ^2.1.1
  usage: ^4.0.0
