name: frontend_server_common
publish_to: none
description: >-
  Frontend server integration code to use for dwds tests. Mimicks flutter code.
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  file: ^6.0.0
  usage: ^4.0.0
  dwds:
    path: ../dwds
