name: webdev_example_app
description: A web app example for webdev CLI.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: ^2.12.0
  webdev: ^2.0.0
