name: webdev_example_app
description: A web app example for webdev CLI.

environment:
  sdk: ">=2.0.0-dev.32.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha+11

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
