name: webdev_example_app
description: A web app example for webdev CLI.

environment:
  sdk: ">=2.2.1-dev.2.0 <3.0.0"

dev_dependencies:
  build_runner: '>=1.3.0 <2.0.0'
  build_web_compilers: '>=1.0.0 <3.0.0'
  build_daemon: ^0.5.0
