name: webdev_example_app
description: A web app example for webdev CLI.

publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  webdev: ^2.7.6
