name: webdev_example_app
description: A web app example for webdev CLI.

environment:
  sdk: ">=2.2.1-dev.2.0 <3.0.0"

dependencies:
  # These ensure the latest angular packages can get a valid version solve
  # with the latest webdev.
  angular: ^5.0.0
  angular_components: ^0.13.0

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=1.0.0 <3.0.0'
  webdev: ^2.0.0
