name: mv3_extension
publish_to: none
version: 2.1.5-wip
description: >-
  A Chrome extension for Dart debugging.

environment:
  sdk: ^3.10.0-0.0.dev

dependencies:
  collection: ^1.19.0
  js: ^0.6.7

dev_dependencies:
  args: ^2.5.0
  build: ^2.4.1
  build_runner: ^2.4.12
  build_web_compilers: ^4.4.1
  dwds: ^24.1.0
  lints: ^6.1.0
  path: ^1.9.0
  sse: ^4.1.4
  test: ^1.26.3
  web_socket_channel: ">=2.2.0 <4.0.0"

dependency_overrides:
  dwds:
    path: ..
