name: frontend_server_client
version: 1.0.0-dev
description: >-
  Client code to start and interact with the frontend_server compiler from the
  Dart SDK.
environment:
  sdk: ">=2.7.0 <2.9.0"
dependencies:
  async: ^2.0.0
  meta: ^1.1.0
  path: ^1.7.0
  uuid: ^2.0.0
dev_dependencies:
  vm_service: ^4.0.0
