name: _testPackage
version: 1.0.0
description: >-
  A fake package used for testing imports. Imports _test.
publish_to: none

environment:
  sdk: ">=2.3.2-dev.0.1 <3.0.0"

dependencies:
  _test:
    path: ../../_test

dev_dependencies:
  build_runner: ^1.6.7
  build_web_compilers: '>=1.0.0 <3.0.0'
