name: _test
version: 1.0.0
description: >-
  A fake package used for testing
publish_to: none

environment:
  sdk: ">=2.3.2-dev.0.1 <3.0.0"

dependencies:
  intl: ^0.15.8
  path: ^1.6.1

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: '>=1.0.0 <3.0.0'
